# Fresh E2E test - No reference manifest (first time enrichment)
publications:
  fresh_test:
    name: "Fresh E2E Test - Online Consultation Oct 2025"
    frequency: monthly
    landing_page: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice
    # No reference_manifest - will use LLM enrichment
    urls:
      - period: oct25
        url: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice/october-2025
