# E2E Test: Online Consultation Feb-June 2025
# Testing full pipeline as documented in docs/pipelines/01_e2e_data_pipeline.md

publications:
  online_consultation_e2e:
    name: "Online Consultation E2E Test"
    frequency: monthly
    landing_page: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice
    reference_manifest: manifests/e2e_test/online_consultation/online_consultation_mar25_enriched.yaml
    urls:
      - period: feb25
        url: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice/february-2025
      - period: mar25
        url: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice/march-2025
      - period: apr25
        url: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice/april-2025
      - period: may25
        url: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice/may-2025
      - period: jun25
        url: https://digital.nhs.uk/data-and-information/publications/statistical/submissions-via-online-consultation-systems-in-general-practice/june-2025
